### ISSUE TITLE
 data constructor TmAscribed  don't defined in Types

### ISSUE THREAD

**Issue by squidCatx** [katsujukou/TaPL-in-PureScript#2]
[1/1 UnknownName] src/TAPL/STLCEx/TypeCheck.purs:65:3

  65    TmAscribed _ tm t2 -> (do
        ^^^^^^^^^^^^^^^^^^

  Unknown data constructor TmAscribed

**Comment by katsujukou** [comment]
Sorry for late replying.
I think this issue is currently fixed up, so  please check.
